### ISSUE TITLE
Mehrere Bücher zurückgeben

### ISSUE THREAD

**Issue by gysel** [koelbener/HSRUInt1GyKoe#15]
Olga will mehrere Bücher von verschiedenen Kunden als zurückgegeben markieren. Weil sie die
Namen der Kunden nicht notiert hat, muss sie für die Rückgabe jeweils die BuchIdentifikationsnummer
angeben.

**Comment by koelbener** [comment]
Geht nun über die Ausleihe Detail View indem man die CopyID eingibt und dann zur vorhandenen Ausleihe srpingt... aber ist noch nicht so optimal

**Comment by gysel** [comment]
Idee: Wenn man eine Ausleihe über das Kontext menu zurückgeben kann, wäre dieses Szenario ziemlich gut abgedeckt.

Was meinst du?

**Comment by koelbener** [comment]
fixed, Massenrückgabe
