### ISSUE TITLE
 Buch zurückgeben welches nicht der Ausleihe entspricht

### ISSUE THREAD

**Issue by gysel** [koelbener/HSRUInt1GyKoe#16]
Er habe aber gleich das Buch neu gekauft und habe gehofft es
würde es niemand merken. Die Exemplarnummern sind schwierig zu fälschen, weil die
Bibliothek diese auf speziell angefertigte Kleber schreibt. Olga erklärt ihm, dass dies kein
Problem sei. Sie markiert das eine Buch als zurückgegeben und das andere als verloren. Das
neu erworbene Buch trägt sie wie gehabt separat ins Inventar ein und klebt eine neue
Exemplarnummer in den Buchdeckel.

**Comment by koelbener** [comment]
Hmm das geht eigentlich oder?
