### ISSUE TITLE
Zustand von Copies muss bearbeitbar sein

### ISSUE THREAD

**Issue by koelbener** [koelbener/HSRUInt1GyKoe#29]
- in der BuchDetailView und bei der Rückgabe

**Comment by gysel** [comment]
auch beheben: die anzahl der Exemplare eines Buchs wird nicht korrekt nachgeführt.

**Comment by gysel** [comment]
Umsetzung bei der Rückgabe noch offen.

**Comment by koelbener** [comment]
Umsetzung bei der Rückgabe umgesetzt. Das Context Menu gefällt mir - aber ist leider noch zu wenig offensichtlich

**Comment by gysel** [comment]
done
