### ISSUE TITLE
paralleles Editieren von Büchern

### ISSUE THREAD

**Issue by koelbener** [koelbener/HSRUInt1GyKoe#30]

**Comment by gysel** [comment]
Aktuelles Verhalten: Wenn ich ein Buch geöffnet habe und ich irgendeine Ausleihe zurückgebe, werden alle Änderungen an meinen Kopien rückgängig gemacht... :(

**Comment by gysel** [comment]
Ein Vorschlag für einen "optimistic locking" approach:

![image.png](https://f.cloud.github.com/assets/1065960/1749/a2202658-412b-11e2-88b9-d5b473d64129.png)
